CREATE TABLE ITEM (
       ITEM_ID  INT AUTO_INCREMENT PRIMARY KEY,
       ITEM_NAME VARCHAR(50) NOT NULL,
       ITEM_ENTERED_BY_USER VARCHAR(20) NOT NULL,
       ITEM_ENTERED_DATE DATE NOT NULL,
       ITEM_BUYING_PRICE NUMERIC NOT NULL,
       ITEM_LAST_MODIFIED_DATE DATE,
       ITEM_LAST_MODIFIED_USER VARCHAR(20),
       ITEM_SELLING_PRICE NUMERIC ,
       ITEM_STATUS VARCHAR(20) NOT NULL
);